config/routes.rb
Rails.application.routes.draw do

  resources :locations
  resources :articles,:users
=begin
    get "/articles" index
    post "/articles" create
    delete "/articles/:id" destroy
    get "/articles/:id" show
    get "/articles/new"  new 
    get "/articles/:id/edit" edit 
    patch "/articles/:id"  update
    put "/articles/:id"    update
=end

  root 'welcome#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new' 
  post '/users ' => 'users#create' 

end

app/models/article.rb
class Article < ActiveRecord::Base
	#la tabla => articles
	#campos => article.title() => 'devuelve el titulo del articulo'
	#Escribir metodos
	#validar que el elemento no este vacio
    #username :username, format: { with: /regex/ }

	validates :title, presence: true, uniqueness: true
	validates :body, presence: true , length: { minimum:10 }
end

app/models/location.rb
class Location < ActiveRecord::Base
	#busca la direccion
	geocoded_by :address
	validates :latitude, presence: true
  	validates :longitude, presence: true 
	#antes de la validacion voy a activar la gema
	after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
#este es el controlador del framework hereda
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#accedo con GET /articles
 def index
 	#todos los articulos del modelo article.rb(tabla)
 	@articles = Article.all 
 end
#GET /articles/:id
 def show 
 	#encontrar un registro por id
	@article = Article.find(params[:id])
 end

 #GET /articles/new 
 #crear un nuevo articulo(no se guarda en la bd solo esta en memoria)
 def new 
 	@article = Article.new
 end
def edit
  @article = Article.find(params[:id]) 
end
#POST /articles
#INSERT INTO
def create
	@article = Article.new(article_params)
#para guardar en la bd
#que si el articulo pudo guardarse(validaciones) y si no no deja crear el articulo
@article.valid?
	if @article.save
		redirect_to @article
	else
		render :new
	end
end


def destroy
	#delete from article
	@article= Article.find(params[:id])
	@article.destroy #elimina el obj de la bd
	redirect_to article_path
end


#PUT /articles/:id
def update
	# @article.update_attributes({title: 'Nuevo titulo'})
end

private
def article_params

	params.require(:article).permit(:title,:body)
	
end


end

app/controllers/gif_controller.rb
class GifController < ApplicationController

  before_filter :authorize

  def cool
  end

  def free
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  #generar marcas,locacion
  def index
    @locations = Location.all
    #@users = User.all
    @hash = Gmaps4rails.build_markers(@locations) do | point, marker|
    marker.lat point.latitude
    marker.lng point.longitude
    marker.json({ title: point.title})
  end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'La localizacion fue creada con éxito.' }
        format.json { render :show, status: :created, location: @location }
        format.js{}
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'La localizacion fue actualizada con éxito.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'La localizacion fue eliminada con éxito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:latitude, :longitude, :address, :description, :title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

#  def new
#  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
    	session[:user_id] = @user.id
    	redirect_to '/'
    else
    redirect_to '/signup'
  end
 end

  private
   def user_params
  	params.require(:user).permit(:name, :email, :password, :password_confirmation)
   end

end

app/controllers/welcome_controller.rb
#hereda de aplication
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<% @article.errors.full_messages.each do |message|%>
<div class="be-black white top-space">
	* <%= message %>
</div>
<%end%>
<div class="field">
	<%= f.text_field :title, placeholder: "Titulo", class:"form-control"%>
</div>

<div class="field">
	<%= f.text_area :body, placeholder: "Escribe aqui el articulo", style:"height:250px;",class:"form-control" %>
</div>
<div class="field">
	<%= f.submit "Guardar", class:"btn be-black white" %>
	
</div>

<%end%>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
	<h1>Editar articulo</h1>
	<%= render "form"%>
</div>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
<h1><%= article.title %></h1>
<div>
	<%= article.body%> - <%= link_to "Eliminar",article,method: :delete%>
</div>
<%end%>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
	<h1>Crear articulo</h1>
    <%= render "form"%>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div>
	<%= @article.body%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyLoc</title>
  <script src="//maps.google.com/maps/api/js?key=AIzaSyALM4Zq6Fq9CtMez2JONP3MYMVkdXHX0Q4"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<link href="https://fonts.googleapis.com/css?family=Bitter:400,700" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <header>
    <nav class="be-black white large-padding">
    <ul class= "no-list row center-xs middle-xs">

    <li class="col-md">
    <h1 class="no-margin" id="logo">MyLoc</h1>	
    </li>

    <li class="col-md">
    <%= link_to "Inicio", root_path %>
    </li>

    <li class="col-md">
      <%= link_to "Locations", "/locations" %>
    </li>

    <li class="col-md">
  <% if current_user %> 
Registrado como <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
    <% else %>
     <li class="col-md">
        <%= link_to 'Login', '/login' %> 
    </li>
    <li class="col-md">
     <%= link_to 'Signup', '/signup' %> 
    </li>
   <% end %>
    </li>

    </ul>
    </nav>	
  </header>
<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location, remote: true  do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editar Localizacion</h1>

<%= render 'form' %>

<%= link_to 'mostrar', @location %> |
<%= link_to 'salir', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Address</th>
      <th>Description</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= location.address %></td>
        <td><%= location.description %></td>
        <td><%= location.title %></td>
        <td><%= link_to 'Mostrar', location %></td>
        <td><%= link_to 'Editar', edit_location_path(location) %></td>
        <td><%= link_to 'Eliminar', location, method: :delete, data: { confirm: 'Deseas eliminarla?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Crear Nueva Localizacion', new_location_path %> <br>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.11.1/jquery-ui.min.js"></script>
  <meta charset="utf-8">
  <script type="text/javascript">
   $(function() {
    $.ajaxSetup( {
      beforeSend: function (xhr) {
        xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'));
      }
    });
  });
    function getPosition() {
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position) {
          var latitude = position.coords.latitude;
          var longitude = position.coords.longitude;
          document.getElementById("latitude").value = latitude;
          document.getElementById("longitude").value = longitude;
          $.post('/locations', {location: { latitude: latitude, longitude: longitude, address:"", description:"", title:""} }, function(response){
            //se envio datos
          });
          alert(latitude +" "+ longitude);
        });
      } else {
        alert("Sorry, your browser does not support HTML5 geolocation.");
      }
    }
  </script>
</head>

<body>

  <label>Latitud: </label>
  <input id="latitude" type="text" name="latitude"</input>
  <label>Longitud: </label>
  <input id="longitude" type="text" name="longitude"</input><br>
  <button type="button" onclick="getPosition();">Obtener lat y long</button>
  <button type="button" onclick="sendPosition();">Enviar</button>
<label id="result"></label>
</body>
</html>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
 handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers(<%=raw @hash.to_json%>);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
}); 
</script>

app/views/locations/new.html.erb
<h1>Nueva Localizacion</h1>

<%= render 'form' %>

<%= link_to 'Salir', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Description:</strong>
  <%= @location.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @location.title %>
</p>

<%= link_to 'Editar', edit_location_path(@location) %> |
<%= link_to 'Salir', locations_path %>

app/views/users/new.html.erb
<div style="width:30%;font-weight:bold;margin:0 auto;font-size:55px;height: 180px; ">
<h1>Registrarse</h1>
</div>

<center>
<%= form_for :user, url: '/users' do |f| %>

  Nombre: <%= f.text_field :name , :class =>'prueba' %><br>
  Email: <%= f.text_field :email, :class =>'prueba'  %><br>
  Contraseña:<%= f.password_field :password, :class => 'prueba' %><br>
  Confirmar:<%= f.password_field :password_confirmation,:class => 'prueba'  %><br>
  <%= f.submit "Enviar", class: 'myButton' %>
  </center>
<% end %>

</div>
</div>

app/views/welcome/index.html.erb
<h1>Bienvenidos a mi Pagina</h1>
<%= link_to "Recurso con Post", "/welcome/index", method: :post %>